// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSQLServer(arg1) {
  return window['go']['main']['App']['ConnectSQLServer'](arg1);
}

export function ConnectServerWithId(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectServerWithId'](arg1, arg2, arg3, arg4);
}

export function ConnectWithProfile(arg1) {
  return window['go']['main']['App']['ConnectWithProfile'](arg1);
}

export function DeleteConnectionProfile(arg1) {
  return window['go']['main']['App']['DeleteConnectionProfile'](arg1);
}

export function DisconnectSQLServer() {
  return window['go']['main']['App']['DisconnectSQLServer']();
}

export function DisconnectServerWithId(arg1) {
  return window['go']['main']['App']['DisconnectServerWithId'](arg1);
}

export function ExecuteNonQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteNonQuery'](arg1, arg2);
}

export function ExecuteNonQueryForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteNonQueryForServer'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteQueryForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQueryForServer'](arg1, arg2, arg3);
}

export function GetRoutineDefinition(arg1, arg2) {
  return window['go']['main']['App']['GetRoutineDefinition'](arg1, arg2);
}

export function GetRoutineDefinitionForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRoutineDefinitionForServer'](arg1, arg2, arg3);
}

export function GetRoutineParameters(arg1, arg2) {
  return window['go']['main']['App']['GetRoutineParameters'](arg1, arg2);
}

export function GetRoutineParametersForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRoutineParametersForServer'](arg1, arg2, arg3);
}

export function GetStatusInfo() {
  return window['go']['main']['App']['GetStatusInfo']();
}

export function GetTableDefinition(arg1, arg2) {
  return window['go']['main']['App']['GetTableDefinition'](arg1, arg2);
}

export function GetTableDefinitionForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableDefinitionForServer'](arg1, arg2, arg3);
}

export function GetTableSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2);
}

export function GetTableSchemaForServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchemaForServer'](arg1, arg2, arg3);
}

export function ListConnectionProfiles() {
  return window['go']['main']['App']['ListConnectionProfiles']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListDatabasesForServer(arg1) {
  return window['go']['main']['App']['ListDatabasesForServer'](arg1);
}

export function ListFunctions(arg1) {
  return window['go']['main']['App']['ListFunctions'](arg1);
}

export function ListFunctionsForServer(arg1, arg2) {
  return window['go']['main']['App']['ListFunctionsForServer'](arg1, arg2);
}

export function ListStoredProcedures(arg1) {
  return window['go']['main']['App']['ListStoredProcedures'](arg1);
}

export function ListStoredProceduresForServer(arg1, arg2) {
  return window['go']['main']['App']['ListStoredProceduresForServer'](arg1, arg2);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function ListTablesForServer(arg1, arg2) {
  return window['go']['main']['App']['ListTablesForServer'](arg1, arg2);
}

export function SaveConnectionProfile(arg1) {
  return window['go']['main']['App']['SaveConnectionProfile'](arg1);
}
