// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectSQLServer(arg1:string):Promise<main.ConnectionResponse>;

export function ConnectServerWithId(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConnectionResponse>;

export function ConnectWithProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionResponse>;

export function DeleteConnectionProfile(arg1:string):Promise<main.ConnectionProfilesResponse>;

export function DisconnectSQLServer():Promise<main.DisconnectResponse>;

export function DisconnectServerWithId(arg1:string):Promise<main.DisconnectResponse>;

export function ExecuteNonQuery(arg1:string,arg2:string):Promise<main.ExecuteQueryResponse>;

export function ExecuteNonQueryForServer(arg1:string,arg2:string,arg3:string):Promise<main.ExecuteQueryResponse>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<main.ExecuteQueryResponse>;

export function ExecuteQueryForServer(arg1:string,arg2:string,arg3:string):Promise<main.ExecuteQueryResponse>;

export function GetRoutineDefinition(arg1:string,arg2:string):Promise<main.RoutineDefinitionResponse>;

export function GetRoutineDefinitionForServer(arg1:string,arg2:string,arg3:string):Promise<main.RoutineDefinitionResponse>;

export function GetRoutineParameters(arg1:string,arg2:string):Promise<main.RoutineParametersResponse>;

export function GetRoutineParametersForServer(arg1:string,arg2:string,arg3:string):Promise<main.RoutineParametersResponse>;

export function GetStatusInfo():Promise<main.StatusInfo>;

export function GetTableDefinition(arg1:string,arg2:string):Promise<main.TableDefinitionResponse>;

export function GetTableDefinitionForServer(arg1:string,arg2:string,arg3:string):Promise<main.TableDefinitionResponse>;

export function GetTableSchema(arg1:string,arg2:string):Promise<main.TableSchemaResponse>;

export function GetTableSchemaForServer(arg1:string,arg2:string,arg3:string):Promise<main.TableSchemaResponse>;

export function ListConnectionProfiles():Promise<main.ConnectionProfilesResponse>;

export function ListDatabases():Promise<main.DatabasesResponse>;

export function ListDatabasesForServer(arg1:string):Promise<main.DatabasesResponse>;

export function ListFunctions(arg1:string):Promise<main.FunctionsResponse>;

export function ListFunctionsForServer(arg1:string,arg2:string):Promise<main.FunctionsResponse>;

export function ListStoredProcedures(arg1:string):Promise<main.StoredProceduresResponse>;

export function ListStoredProceduresForServer(arg1:string,arg2:string):Promise<main.StoredProceduresResponse>;

export function ListTables(arg1:string):Promise<main.TablesResponse>;

export function ListTablesForServer(arg1:string,arg2:string):Promise<main.TablesResponse>;

export function SaveConnectionProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionProfilesResponse>;
